### ISSUE TITLE
Release checklist for 0.5.6

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Organization#50]
Checklist for Thrive release (these should roughly happen in order):

- [x] 9 days before release: check open PRs to see if any is close enough to done so that they can be pushed to be finished
- [x] Ask on discord if people are up for a release podcast
- [x] Mention on discord that feature freeze has started
- [x] 7 days before release: merge open PRs from weblate (first push all pending changes from weblate)
- [x] Run scripts/update_translation_progress.rb
- [x] Make a release candidate and post on the community forums and discord (use DevCenter file hosting for the downloads)
- [x] Upload RC also to beta channel on game stores
- [x] Post announcement on Weblate when deadline for translations is (2 days before the release at the end of the day)
- [x] Enable the auto comment on PRs about feature freeze
- [x] Start drafting the release on Github
- [x] Post the patch notes draft on discord so that devblog can start
- [x] Get someone (or our usual trailer guy) to start working on a trailer
- [x] Make a livestream event on Youtube if there are probably enough people for it. Optional: make pre-stream questions for general audience
- [x] Make high priority questions thread for the VIP patrons
- [x] 1 day before release: merge last small fix PRs
- [x] Merge last translations PR (first push all pending changes from weblate)
- [x] Make sure trailer is ready to go
- [x] Run scripts/update_translation_progress.rb
- [x] Update credits with scripts/retrieve_credits.rb
- [x] On the day of release: compile and upload builds to Github release draft
- [x] Push the release version to the stable channel for game stores
- [x] Publish the release on Github
- [x] Update the launcher repo to have the new version listed in the launcher
- [x] Publish the trailer on our Youtube channel
- [x] Publish the devblog
- [x] Link the release on Github to the devblog and link the trailer in the devblog
- [x] After the release: turn the auto comment to Github off
- [x] Post general feedback thread on the community forums
- [x] Have the release livestream
